defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: jukebox_jonjo_server_development

test:
  <<: *defaults
  database: jukebox_jonjo_server_test

# set these environment variables on your prod server
production:
  host: <%= ENV['MONGOID_HOST'] %>
  port: <%= ENV['MONGOID_PORT'] %>
  database: <%= ENV['MONGOID_DATABASE'] %>
  username: <%= ENV['MONGOID_USERNAME'] %>
  password: <%= ENV['MONGOID_PASSWORD'] %>
